### ISSUE TITLE
Development DB for Local Development

### ISSUE THREAD

**Issue by paullpp** [paullpp/hemp-db#42]
We've been using the same database for production and local development, which can cause issues when making changes to the DB locally, and migrating those changes before deploying your code to production.

To circumvent that we'll need to set up a database for development. This doesn't have to be hosted in the cloud, we can spin up a mysql image in docker, and initialize it to be an empty version of our production database

**Comment by meithofdOSU** [comment]
Local DB setup for development. To change the database for local development go to the .env file and change the MYSQL_Name = local_db.
